algoritmo "TipoDados"
var
    nome: caractere
    idade: inteiro
    altura: real
    crianca: logico

inicio

    escreva("Digite o seu nome: ", nome)
    leia(nome)
    escreval("Seu nome é ", nome)

    escreva("Digite a sua idade: ")
    leia(idade)
    escreval("Sua idade é ", idade)

    escreva("Digite a sua altura: ")
    leia(altura)
    escreval("Sua altura é ", altura)

    escreva("Você é criança? (S/N): ")
    leia(crianca)
    escreval("É ", crianca)

fimalgoritmo